export const colors = {
  primary: '#1e5c3a',
  primaryDark: '#2C4A3E',
  primaryMid: '#3A6455',
  background: '#f0f0ee',
  backgroundLight: '#F7F8F6',
  white: '#ffffff',
  textDark: '#1a1a1a',
  textMid: '#2a2a2a',
  textLight: '#b0b0b0',
  textFaint: '#c0c0c0',
  border: '#ebebeb',
  borderMid: '#DFE3DD',
  inputBg: '#EDEFEC',
  badgeGreenBg: '#e4f2ea',
  badgeRedBg: '#fde8e8',
  badgeRed: '#d9534f',
  notifRed: '#e74c3c',
  cardBorder: '#e8e8e8',
  chipBorder: '#d0d0d0',
  chipText: '#555555',
  navbarBg: '#ffffff',
}
